## Quaternions

In the following exercise we implement functions to convert between Euler angles and quaternion representations.

It's useful to be able to easily navigate back and forth between these representations because of their relative strengths. Quaternions are better for calculations, while Euler angles are far more intuitive.

Some messages coming from your drone in simulation (or in the real world) will represent orientation data as a quaternion, while others use Euler angles. So it's a good idea to be able to seamlessly handle both. 

The [`udacidrone` API imlementation](https://github.com/udacity/udacidrone/blob/master/udacidrone/connection/message_types.py#L189-L284) that we are using for the projects in this program already has these conversions implemented under the hood so that's a great place to look for inspiration.

In [48]:
import numpy as np

def euler_to_quaternion(angles):
    '''
    Function to convert from Euler angles to Quaternion.
    
    Input: numnpy array of 3 elements represening roll, pitch and
           yaw angles [roll, pitch, yaw] expressed in radians
    
    Output: numpy array of 4 elements representing a 
            quaternion [a, b, c, d]
    '''
    roll = angles[0]
    pitch = angles[1]
    yaw = angles[2]
    
    # Conversion
    a = (np.cos(roll/2) * np.cos(pitch/2) * np.cos(yaw/2) +
         np.sin(roll/2) * np.sin(pitch/2) * np.sin(yaw/2))
    
    b = (np.sin(roll/2) * np.cos(pitch/2) * np.cos(yaw/2) -
        np.cos(roll/2) * np.sin(pitch/2) * np.sin(yaw/2))
    
    c = (np.cos(roll/2) * np.sin(pitch/2) * np.cos(yaw/2) +
        np.sin(roll/2) * np.cos(pitch/2) * np.sin(yaw/2))
    
    d = (np.cos(roll/2) * np.cos(pitch/2) * np.sin(yaw/2) -
        np.sin(roll/2) * np.sin(pitch/2) * np.cos(yaw/2))
    
    return np.array([a, b, c, d])

def quaternion_to_euler(quaternion):
    '''
    Function to convert from Quaternion to Euler angles.
    
    Input: numpy array of 4 elements representing a 
            quaternion [a, b, c, d]
            
    Output: numnpy array of 3 elements represening roll, pitch and
           yaw angles [roll, pitch, yaw] expressed in radians
    
    
    '''
    a = quaternion[0]
    b = quaternion[1]
    c = quaternion[2]
    d = quaternion[3]
    
    # Conversion
    roll = np.arctan2(2 * (a * b + c * d), (1 - 2 * (b**2 + c**2)))
    pitch = np.arcsin(2 * (a * c - d * b))
    yaw = np.arctan2(2 * (a * d + b * c), (1 - 2 * (c**2 + d**2)))

    return np.array([roll, pitch, yaw])

Test the conversion.

In [77]:
# Euler angles to convert: roll=90º, pitch=30º, yaw=0º
euler_angles = np.array([np.deg2rad(90), np.deg2rad(30), np.deg2rad(0)])
print(np.rad2deg(euler_angles))

# Conversion from Euler angles to quaternion
q = euler_to_quaternion(euler_angles) # should be [ 0.683  0.683  0.183 -0.183]
print(q)

# Convert back the previous quaternioun q to Euler angles
e = quaternion_to_euler(q) # should be [ 1.570  0.523  0.] in radians
print(e)
print(np.rad2deg(e))

[90. 30.  0.]
[ 0.6830127  0.6830127  0.1830127 -0.1830127]
[1.57079633 0.52359878 0.        ]
[90. 30.  0.]
